// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stitch.proto

package giraffe

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Stitch struct {
	// Service is the fully-qualified package and
	// service name of the service, e.g. namely.profiles.ProfilesService
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Method is the method to call within the service, e.g GetProfile
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Request Parameter is the name of the field within the request type
	// to set. The value of this field will be the value of the annotated
	// stitch option.
	RequestParameter string `protobuf:"bytes,3,opt,name=request_parameter,json=requestParameter,proto3" json:"request_parameter,omitempty"`
	// Field name is the name of the field which will be added to the GraphQL
	// schema
	FieldName string `protobuf:"bytes,4,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	// Hide field will hide the source field from the schema so only the stitched
	// object is present
	HideField bool `protobuf:"varint,5,opt,name=hide_field,json=hideField,proto3" json:"hide_field,omitempty"`
	// Request Quantifier is an optional quantifier for the method payload (e.g.
	// byEmployment). The value of this field will act as a key for the payload {
	// [requestQuantifier]: { [requestParamter]: <value> }}
	RequestQuantifier    string   `protobuf:"bytes,6,opt,name=request_quantifier,json=requestQuantifier,proto3" json:"request_quantifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stitch) Reset()         { *m = Stitch{} }
func (m *Stitch) String() string { return proto.CompactTextString(m) }
func (*Stitch) ProtoMessage()    {}
func (*Stitch) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f2f474817018ccd, []int{0}
}

func (m *Stitch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stitch.Unmarshal(m, b)
}
func (m *Stitch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stitch.Marshal(b, m, deterministic)
}
func (m *Stitch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stitch.Merge(m, src)
}
func (m *Stitch) XXX_Size() int {
	return xxx_messageInfo_Stitch.Size(m)
}
func (m *Stitch) XXX_DiscardUnknown() {
	xxx_messageInfo_Stitch.DiscardUnknown(m)
}

var xxx_messageInfo_Stitch proto.InternalMessageInfo

func (m *Stitch) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Stitch) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Stitch) GetRequestParameter() string {
	if m != nil {
		return m.RequestParameter
	}
	return ""
}

func (m *Stitch) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *Stitch) GetHideField() bool {
	if m != nil {
		return m.HideField
	}
	return false
}

func (m *Stitch) GetRequestQuantifier() string {
	if m != nil {
		return m.RequestQuantifier
	}
	return ""
}

var E_Stitch = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Stitch)(nil),
	Field:         165218,
	Name:          "namely.giraffe.stitch",
	Tag:           "bytes,165218,opt,name=stitch",
	Filename:      "stitch.proto",
}

func init() {
	proto.RegisterType((*Stitch)(nil), "namely.giraffe.Stitch")
	proto.RegisterExtension(E_Stitch)
}

func init() { proto.RegisterFile("stitch.proto", fileDescriptor_9f2f474817018ccd) }

var fileDescriptor_9f2f474817018ccd = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0xa9, 0x7f, 0xba, 0x76, 0x14, 0xd1, 0x1c, 0x96, 0x20, 0x2c, 0x14, 0x4f, 0x0b, 0x62,
	0x16, 0xf4, 0xe6, 0xd1, 0x83, 0x47, 0x57, 0xeb, 0xcd, 0x4b, 0xc9, 0xb6, 0x93, 0x36, 0xd0, 0x36,
	0xdd, 0x24, 0x15, 0x7c, 0x05, 0x9f, 0xcf, 0x27, 0xf0, 0x49, 0xa4, 0xd3, 0x46, 0xf0, 0x38, 0xdf,
	0x6f, 0xf2, 0x65, 0xf8, 0xc1, 0x99, 0xf3, 0xda, 0x17, 0xb5, 0xe8, 0xad, 0xf1, 0x86, 0x9d, 0x77,
	0xb2, 0xc5, 0xe6, 0x53, 0x54, 0xda, 0x4a, 0xa5, 0xf0, 0x2a, 0xad, 0x8c, 0xa9, 0x1a, 0xdc, 0x10,
	0xdd, 0x0d, 0x6a, 0x53, 0xa2, 0x2b, 0xac, 0xee, 0xbd, 0xb1, 0xd3, 0x8b, 0xeb, 0xef, 0x08, 0xe2,
	0x37, 0xaa, 0x60, 0x1c, 0x16, 0x0e, 0xed, 0x87, 0x2e, 0x90, 0x47, 0x69, 0xb4, 0x4e, 0xb2, 0x30,
	0xb2, 0x25, 0xc4, 0x2d, 0xfa, 0xda, 0x94, 0xfc, 0x80, 0xc0, 0x3c, 0xb1, 0x1b, 0xb8, 0xb4, 0xb8,
	0x1f, 0xd0, 0xf9, 0xbc, 0x97, 0x56, 0xb6, 0xe8, 0xd1, 0xf2, 0x43, 0x5a, 0xb9, 0x98, 0xc1, 0x4b,
	0xc8, 0xd9, 0x0a, 0x40, 0x69, 0x6c, 0xca, 0x7c, 0xbc, 0x91, 0x1f, 0xd1, 0x56, 0x42, 0xc9, 0xb3,
	0x6c, 0x71, 0xc4, 0xb5, 0x2e, 0x31, 0xa7, 0x84, 0x1f, 0xa7, 0xd1, 0xfa, 0x24, 0x4b, 0xc6, 0xe4,
	0x69, 0x0c, 0xd8, 0x2d, 0xb0, 0xf0, 0xd5, 0x7e, 0x90, 0x9d, 0xd7, 0x4a, 0xa3, 0xe5, 0x31, 0xb5,
	0x84, 0x23, 0x5e, 0xff, 0xc0, 0xc3, 0x16, 0xe2, 0x49, 0x0c, 0x5b, 0x89, 0xc9, 0x81, 0x08, 0x0e,
	0x04, 0x15, 0x6e, 0x7b, 0xaf, 0x4d, 0xe7, 0xf8, 0xcf, 0x17, 0xa4, 0xd1, 0xfa, 0xf4, 0x6e, 0x29,
	0xfe, 0xab, 0x13, 0x93, 0x94, 0x6c, 0xae, 0x79, 0x4c, 0xde, 0x17, 0x33, 0xd9, 0xc5, 0xd4, 0x74,
	0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x81, 0x6f, 0x7c, 0x7b, 0x01, 0x00, 0x00,
}
