// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: namely/giraffe/stitch.proto

package giraffe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stitch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Service is the fully-qualified package and
	// service name of the service, e.g. namely.profiles.ProfilesService
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Method is the method to call within the service, e.g GetProfile
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Request Parameter is the name of the field within the request type
	// to set. The value of this field will be the value of the annotated
	// stitch option.
	RequestParameter string `protobuf:"bytes,3,opt,name=request_parameter,json=requestParameter,proto3" json:"request_parameter,omitempty"`
	// Field name is the name of the field which will be added to the GraphQL
	// schema
	FieldName string `protobuf:"bytes,4,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	// Hide field will hide the source field from the schema so only the stitched
	// object is present
	HideField bool `protobuf:"varint,5,opt,name=hide_field,json=hideField,proto3" json:"hide_field,omitempty"`
	// Request Quantifier is an optional quantifier for the method payload (e.g.
	// byEmployment). The value of this field will act as a key for the payload {
	// [requestQuantifier]: { [requestParamter]: <value> }}
	RequestQuantifier string `protobuf:"bytes,6,opt,name=request_quantifier,json=requestQuantifier,proto3" json:"request_quantifier,omitempty"`
}

func (x *Stitch) Reset() {
	*x = Stitch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_namely_giraffe_stitch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stitch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stitch) ProtoMessage() {}

func (x *Stitch) ProtoReflect() protoreflect.Message {
	mi := &file_namely_giraffe_stitch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stitch.ProtoReflect.Descriptor instead.
func (*Stitch) Descriptor() ([]byte, []int) {
	return file_namely_giraffe_stitch_proto_rawDescGZIP(), []int{0}
}

func (x *Stitch) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Stitch) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Stitch) GetRequestParameter() string {
	if x != nil {
		return x.RequestParameter
	}
	return ""
}

func (x *Stitch) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *Stitch) GetHideField() bool {
	if x != nil {
		return x.HideField
	}
	return false
}

func (x *Stitch) GetRequestQuantifier() string {
	if x != nil {
		return x.RequestQuantifier
	}
	return ""
}

var file_namely_giraffe_stitch_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Stitch)(nil),
		Field:         165218,
		Name:          "namely.giraffe.stitch",
		Tag:           "bytes,165218,opt,name=stitch",
		Filename:      "namely/giraffe/stitch.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional namely.giraffe.Stitch stitch = 165218;
	E_Stitch = &file_namely_giraffe_stitch_proto_extTypes[0]
)

var File_namely_giraffe_stitch_proto protoreflect.FileDescriptor

var file_namely_giraffe_stitch_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6e, 0x61, 0x6d, 0x65, 0x6c, 0x79, 0x2f, 0x67, 0x69, 0x72, 0x61, 0x66, 0x66, 0x65,
	0x2f, 0x73, 0x74, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6e,
	0x61, 0x6d, 0x65, 0x6c, 0x79, 0x2e, 0x67, 0x69, 0x72, 0x61, 0x66, 0x66, 0x65, 0x1a, 0x20, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xd4, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x69, 0x74, 0x63, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x2b, 0x0a, 0x11,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x69, 0x64, 0x65,
	0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x68, 0x69,
	0x64, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x11, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x51, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x3a, 0x4f, 0x0a, 0x06, 0x73, 0x74, 0x69, 0x74, 0x63, 0x68,
	0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0xe2, 0x8a, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6c, 0x79,
	0x2e, 0x67, 0x69, 0x72, 0x61, 0x66, 0x66, 0x65, 0x2e, 0x53, 0x74, 0x69, 0x74, 0x63, 0x68, 0x52,
	0x06, 0x73, 0x74, 0x69, 0x74, 0x63, 0x68, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x6c, 0x79, 0x2f, 0x67, 0x69, 0x72,
	0x61, 0x66, 0x66, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x67, 0x69, 0x72, 0x61, 0x66,
	0x66, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_namely_giraffe_stitch_proto_rawDescOnce sync.Once
	file_namely_giraffe_stitch_proto_rawDescData = file_namely_giraffe_stitch_proto_rawDesc
)

func file_namely_giraffe_stitch_proto_rawDescGZIP() []byte {
	file_namely_giraffe_stitch_proto_rawDescOnce.Do(func() {
		file_namely_giraffe_stitch_proto_rawDescData = protoimpl.X.CompressGZIP(file_namely_giraffe_stitch_proto_rawDescData)
	})
	return file_namely_giraffe_stitch_proto_rawDescData
}

var file_namely_giraffe_stitch_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_namely_giraffe_stitch_proto_goTypes = []interface{}{
	(*Stitch)(nil),                    // 0: namely.giraffe.Stitch
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_namely_giraffe_stitch_proto_depIdxs = []int32{
	1, // 0: namely.giraffe.stitch:extendee -> google.protobuf.FieldOptions
	0, // 1: namely.giraffe.stitch:type_name -> namely.giraffe.Stitch
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_namely_giraffe_stitch_proto_init() }
func file_namely_giraffe_stitch_proto_init() {
	if File_namely_giraffe_stitch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_namely_giraffe_stitch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stitch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_namely_giraffe_stitch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_namely_giraffe_stitch_proto_goTypes,
		DependencyIndexes: file_namely_giraffe_stitch_proto_depIdxs,
		MessageInfos:      file_namely_giraffe_stitch_proto_msgTypes,
		ExtensionInfos:    file_namely_giraffe_stitch_proto_extTypes,
	}.Build()
	File_namely_giraffe_stitch_proto = out.File
	file_namely_giraffe_stitch_proto_rawDesc = nil
	file_namely_giraffe_stitch_proto_goTypes = nil
	file_namely_giraffe_stitch_proto_depIdxs = nil
}
